[package]
name = "moar-horse-solve"
version = "1.0.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.3"
solana-program = "1.8.14"
moar-horse = { version = "1.0.0", path = "../program", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
